In [2]:
%matplotlib inline

import numpy as np
import statsmodels.api as sm

In [7]:
nsample = 50
sig = 0.25
x1 = np.linspace(0, 20, nsample)
X = np.column_stack((x1, np.sin(x1), (x1-5)**2))
#X = sm.add_constant(X)
beta = [5., 0.5, 0.5, -0.02]
y_true = np.dot(X, beta)
y = y_true + sig * np.random.normal(size=nsample)

ValueError: shapes (50,3) and (4,) not aligned: 3 (dim 1) != 4 (dim 0)

In [4]:
print(X)

[[  1.00000000e+00   0.00000000e+00   0.00000000e+00   2.50000000e+01]
 [  1.00000000e+00   4.08163265e-01   3.96924149e-01   2.10849646e+01]
 [  1.00000000e+00   8.16326531e-01   7.28634783e-01   1.75031237e+01]
 [  1.00000000e+00   1.22448980e+00   9.40632785e-01   1.42544773e+01]
 [  1.00000000e+00   1.63265306e+00   9.98087482e-01   1.13390254e+01]
 [  1.00000000e+00   2.04081633e+00   8.91559230e-01   8.75676801e+00]
 [  1.00000000e+00   2.44897959e+00   6.38550320e-01   6.50770512e+00]
 [  1.00000000e+00   2.85714286e+00   2.80629400e-01   4.59183673e+00]
 [  1.00000000e+00   3.26530612e+00  -1.23398137e-01   3.00916285e+00]
 [  1.00000000e+00   3.67346939e+00  -5.07151709e-01   1.75968347e+00]
 [  1.00000000e+00   4.08163265e+00  -8.07581691e-01   8.43398584e-01]
 [  1.00000000e+00   4.48979592e+00  -9.75328286e-01   2.60308205e-01]
 [  1.00000000e+00   4.89795918e+00  -9.82831204e-01   1.04123282e-02]
 [  1.00000000e+00   5.30612245e+00  -8.28857736e-01   9.37109538e-02]
 [  1.